
flib_version=1.0.0-SNAPSHOT

mod_id=creeperheal
curse_slug=forge-creeper-heal-unofficial
curse_id=246973
mod_version=2.0.3
mod_name=CreeperHeal
mod_group_id=com.lothrazar.creeperheal
mod_license=SeeGithub
mod_authors=EyZox, Lothrazar 
mod_description=mod
