

mod_id=creeperheal
curse_slug=forge-creeper-heal-unofficial
curse_id=246973
mod_version=2.0.4
mod_name=CreeperHeal
mod_group_id=com.lothrazar.creeperheal
mod_license=SeeGithub
mod_authors=EyZox, Lothrazar 
mod_description=mod
modrinth_id=creeper-heal

flib_version=0.2.0
flib_file=8117455


